// Generated by CoffeeScript 1.3.3
var LOGIN_KEYS, User, Utils, models;

models = require('../models/models');

Utils = require('./utils').Utils;

User = models.User;

LOGIN_KEYS = ["input_id", "input_passwd"];

exports.login = function(req, res) {
  var _params;
  _params = req.body || {};
  if (!Utils.checkParams(_params, LOGIN_KEYS)) {
    res.redirect('/');
  }
  return User.find({
    user_id: _params.input_id
  }, function(err, docs) {
    var dbPass, queryPass, user;
    if (docs.length === 1) {
      user = docs[0];
      dbPass = Utils.getCrypto(user.passwd);
      queryPass = Utils.getCrypto(_params.input_passwd);
      if (dbPass === queryPass) {
        res.redirect('/list');
        return;
      }
    }
    return res.redirect('/');
  });
};

exports.list = function(req, res) {
  return res.render("list", Utils.pageInfo(req));
};

exports.search = function(req, res) {
  var _data;
  res.contentType('application/json');
  _data = [
    {
      no: 1,
      filename: 'test_file.zip',
      size: 100,
      created: new Date
    }, {
      no: 2,
      filename: 'test_file2.zip',
      size: 100,
      created: new Date
    }, {
      no: 3,
      filename: 'test_file3.zip',
      size: 100,
      created: new Date
    }
  ];
  return res.send(_data);
};
