// Generated by CoffeeScript 1.8.0
var crypto, _;

_ = require('underscore');

crypto = require('crypto');

exports.Utils = {
  checkParams: function(params, defines) {
    var _keys, _ret;
    _keys = _.keys(params);
    _ret = true;
    _.each(defines, function(d) {
      if (!_.contains(_keys, d)) {
        return _ret = false;
      }
    });
    return _ret;
  },
  getCrypto: function(d) {
    return d;
  },
  pageInfo: function(req) {
    var conf;
    conf = {
      title: "Meriazard",
      url: req.route.path.replace('/', '')
    };
    return conf;
  },
  dateFormat: function(o) {
    return "test";
  }
};
